import Breadcrumb from "../components/layout/breadcrumb/Breadcrumb";
import HeaderSection from "../components/contact/content/ContentSection";
import ContactForm from "../components/contact/form/ContactForm";
import Layout from "../components/layout/Layout";
import Head from 'next/head';
import useTranslation from "next-translate/useTranslation";
const contact = () => {
  const {t} = useTranslation()
  const props = {
    title: t("common:contact"),
  };
  // console.log(t)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Layout>
        <Breadcrumb props={props}/>

        {/*{'common'.'Contact'}*/}
        <HeaderSection/>
        <ContactForm/>
      </Layout>
    </>
  );
};
export default contact;
