import {HeroSlider} from "../components/Home/hero/HeroSlider";
import {AboutUsHome} from "../components/Home/about-us/AboutUs";
import {Services} from "../components/Home/service/Servcie";
import {GridSection} from "../components/Home/GridSection/GridSection";
import {ClientSection} from "../components/Home/ClientsSection/ClientSection";
import {FeedbackSectionStyle1} from "../components/Home/feedbacks/FeedbackSection";
import Layout from "../components/layout/Layout";

export default function Home() {
    let aspect = {height: '100vh', width: '100vw'}
    return (
      <Layout>
            <HeroSlider aspect={{...aspect, hasLetters: true}}/>
            <AboutUsHome/>
            <Services/>
            <HeroSlider aspect={aspect}/>
            <GridSection/>
            <ClientSection/>
            <FeedbackSectionStyle1/>
        </Layout>
    )
}

{/*<Head>*/
}
{/*    <title>Create Next App</title>*/
}
{/*    <meta name="description" content="Generated by create next app"/>*/
}
{/*    <link rel="icon" href="/favicon.ico"/>*/
}
{/*</Head>*/
}
{/*<h2> Single Item</h2>*/
}
{/*<div style={{overflow:'hidden'}}>*/
}

{/*</div>*/
}